[versions]
agp = "8.0.0"
cardview = "1.0.0"
compiler = "4.16.0"
escposThermalprinterAndroid = "3.3.0"
itext7Core = "7.2.5"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.1"
lifecycleLivedata = "2.9.1"
material = "1.12.0"
activity = "1.10.1"
constraintlayout = "2.2.1"
navigationFragment = "2.9.1"
preference = "1.2.1"
recyclerview = "1.4.0"
roomKtx = "2.7.2"
threetenabp = "1.4.6"
workRuntime = "2.10.2"

[libraries]
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata", version.ref = "lifecycleLivedata" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleLivedata" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleLivedata" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomKtx" }
cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
escpos-thermalprinter-android = { module = "com.github.DantSu:ESCPOS-ThermalPrinter-Android", version.ref = "escposThermalprinterAndroid" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "compiler" }
itext7-core = { module = "com.itextpdf:itext7-core", version.ref = "itext7Core" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
work-runtime = { module = "androidx.work:work-runtime", version.ref = "workRuntime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

